-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 00:09:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TransportManagerDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TransportManagerDB` ;

-- -----------------------------------------------------
-- Schema TransportManagerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TransportManagerDB` DEFAULT CHARACTER SET UTF8MB4 ;
USE `TransportManagerDB` ;

-- -----------------------------------------------------
-- Table `TransportManagerDB`.`Kierowca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManagerDB`.`Kierowca` ;

CREATE TABLE IF NOT EXISTS `TransportManagerDB`.`Kierowca` (
  `idKierowca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `nrTel` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idKierowca`),
  UNIQUE INDEX `idKierowcy_UNIQUE` (`idKierowca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransportManagerDB`.`Pojazd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManagerDB`.`Pojazd` ;

CREATE TABLE IF NOT EXISTS `TransportManagerDB`.`Pojazd` (
  `idPojazd` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idKierowca` INT UNSIGNED NULL,
  `typPojazdu` ENUM('Ciągnik', 'Naczepa') NOT NULL,
  `marka` VARCHAR(20) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `nrRejestracyjny` VARCHAR(8) NOT NULL,
  `dodatkoweInf` VARCHAR(100) NULL,
  PRIMARY KEY (`idPojazd`),
  UNIQUE INDEX `idPojazd_UNIQUE` (`idPojazd` ASC) VISIBLE,
  INDEX `idKierowcy_idx` (`idKierowca` ASC) INVISIBLE,
  CONSTRAINT `idKierowca_fk`
    FOREIGN KEY (`idKierowca`)
    REFERENCES `TransportManagerDB`.`Kierowca` (`idKierowca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransportManagerDB`.`TypSerwisu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManagerDB`.`TypSerwisu` ;

CREATE TABLE IF NOT EXISTS `TransportManagerDB`.`TypSerwisu` (
  `idTypSerwisu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rodzajSerwisu` VARCHAR(100) NOT NULL,
  `typPojazdu` ENUM('Ciągnik', 'Naczepa') NOT NULL,
  PRIMARY KEY (`idTypSerwisu`),
  UNIQUE INDEX `idTypSerwisu_UNIQUE` (`idTypSerwisu` ASC) VISIBLE,
  UNIQUE INDEX `rodzaj_typ_UNIQUE` (`rodzajSerwisu`, `typPojazdu`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransportManagerDB`.`Serwis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManagerDB`.`Serwis` ;

CREATE TABLE IF NOT EXISTS `TransportManagerDB`.`Serwis` (
  `idSerwis` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPojazd` INT UNSIGNED NOT NULL,
  `idTypSerwisu` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `cenaCzesciNetto` INT NULL,
  `robocizna` INT NULL,
  `kosztCalkowityNetto` INT NOT NULL,
  `przebieg` INT NULL,
  `infoDodatkowe` VARCHAR(200) NULL,
  PRIMARY KEY (`idSerwis`),
  UNIQUE INDEX `idSerwisy_UNIQUE` (`idSerwis` ASC) VISIBLE,
  INDEX `idTypSerwisu_idx` (`idTypSerwisu` ASC) VISIBLE,
  INDEX `idPojazd_idx` (`idPojazd` ASC) VISIBLE,
  CONSTRAINT `idPojazd_serwis_fk`
    FOREIGN KEY (`idPojazd`)
    REFERENCES `TransportManagerDB`.`Pojazd` (`idPojazd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTypSerwisu_serwis_fk`
    FOREIGN KEY (`idTypSerwisu`)
    REFERENCES `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransportManagerDB`.`Część`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManagerDB`.`Część` ;

CREATE TABLE IF NOT EXISTS `TransportManagerDB`.`Część` (
  `idCzesc` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idTypSerwisu` INT UNSIGNED NOT NULL,
  `nazwaElementu` VARCHAR(100) NOT NULL,
  `ilosc` INT NOT NULL,
  PRIMARY KEY (`idCzesc`),
  UNIQUE INDEX `idMagazyn_UNIQUE` (`idCzesc` ASC) VISIBLE,
  INDEX `idTypSerwisu_idx` (`idTypSerwisu` ASC) VISIBLE,
  CONSTRAINT `idTypSerwisu_czesc_fk`
    FOREIGN KEY (`idTypSerwisu`)
    REFERENCES `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TransportManagerDB`.`WyposażeniePojazdu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManagerDB`.`WyposażeniePojazdu` ;

CREATE TABLE IF NOT EXISTS `TransportManagerDB`.`WyposażeniePojazdu` (
  `idWyposazeniePojazdu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPojazd` INT UNSIGNED NOT NULL,
  `opis` VARCHAR(100) NOT NULL,
  `ilosc` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idWyposazeniePojazdu`),
  UNIQUE INDEX `idWyposażeniePojazdu_UNIQUE` (`idWyposazeniePojazdu` ASC) VISIBLE,
  INDEX `idPojazd_idx` (`idPojazd` ASC) VISIBLE,
  CONSTRAINT `idPojazd_wyposazenie_fk`
    FOREIGN KEY (`idPojazd`)
    REFERENCES `TransportManagerDB`.`Pojazd` (`idPojazd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `TransportManagerDB`;

DELIMITER $$

USE `TransportManagerDB`$$
DROP TRIGGER IF EXISTS `TransportManagerDB`.`Serwisy_BEFORE_INSERT` $$
USE `TransportManagerDB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `TransportManagerDB`.`Serwisy_BEFORE_INSERT` BEFORE INSERT ON `Serwis` FOR EACH ROW
BEGIN
IF NEW.kosztCalkowityNetto IS NULL THEN
        SET NEW.kosztCalkowityNetto = COALESCE(NEW.cenaCzesciNetto, 0) + COALESCE(NEW.robocizna, 0);
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TransportManagerDB`.`Kierowca`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManagerDB`;
INSERT INTO `TransportManagerDB`.`Kierowca` (`idKierowca`, `imie`, `nazwisko`, `nrTel`) VALUES (1, 'Jan', 'Kowalski', '893938783');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManagerDB`.`Pojazd`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManagerDB`;
INSERT INTO `TransportManagerDB`.`Pojazd` (`idPojazd`, `idKierowca`, `typPojazdu`, `marka`, `model`, `nrRejestracyjny`, `dodatkoweInf`) VALUES (1, 1, 'Ciągnik', 'Volvo', 'optimus', 'POS34902', 'czerwony');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManagerDB`.`TypSerwisu`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManagerDB`;
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Opony', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Hamulce', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Silnik', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Wyposażenie', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Zawieszenie', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Klimatyzacja', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Układ chłodniczy', 'Ciągnik');
INSERT INTO `TransportManagerDB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES (DEFAULT, 'Inne', 'Ciągnik');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManagerDB`.`Część`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManagerDB`;
INSERT INTO `TransportManagerDB`.`Część` (`idCzesc`, `idTypSerwisu`, `nazwaElementu`, `ilosc`) VALUES (DEFAULT, 1, 'Opona 195x55xR16 Dunlop', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManagerDB`.`WyposażeniePojazdu`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManagerDB`;
INSERT INTO `TransportManagerDB`.`WyposażeniePojazdu` (`idWyposazeniePojazdu`, `idPojazd`, `opis`, `ilosc`) VALUES (DEFAULT, 1, 'Gaśnica', 1);

COMMIT;
