-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 00:09:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TransportManager2DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TransportManager2DB` ;

-- -----------------------------------------------------
-- Schema TransportManager2DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TransportManager2DB` DEFAULT CHARACTER SET UTF8MB4 ;
USE `TransportManager2DB` ;

-- -----------------------------------------------------
-- Table `TransportManager2DB`.`Kierowca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManager2DB`.`Kierowca` ;

CREATE TABLE IF NOT EXISTS `TransportManager2DB`.`Kierowca` (
  `idKierowca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `nrTel` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idKierowca`),
  UNIQUE INDEX `idKierowcy_UNIQUE` (`idKierowca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransportManager2DB`.`Pojazd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManager2DB`.`Pojazd` ;

CREATE TABLE IF NOT EXISTS `TransportManager2DB`.`Pojazd` (
  `idPojazd` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idKierowca` INT UNSIGNED NULL,
  `typPojazdu` ENUM('Ciągnik', 'Naczepa') NOT NULL,
  `marka` VARCHAR(20) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `nrRejestracyjny` VARCHAR(8) NOT NULL,
  `dodatkoweInf` VARCHAR(100) NULL,
  PRIMARY KEY (`idPojazd`),
  UNIQUE INDEX `idPojazd_UNIQUE` (`idPojazd` ASC) VISIBLE,
  INDEX `idKierowcy_idx` (`idKierowca` ASC) INVISIBLE,
  CONSTRAINT `idKierowca_fk`
    FOREIGN KEY (`idKierowca`)
    REFERENCES `TransportManager2DB`.`Kierowca` (`idKierowca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransportManager2DB`.`TypSerwisu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManager2DB`.`TypSerwisu` ;

CREATE TABLE IF NOT EXISTS `TransportManager2DB`.`TypSerwisu` (
  `idTypSerwisu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rodzajSerwisu` VARCHAR(100) NOT NULL,
  `typPojazdu` ENUM('Ciągnik', 'Naczepa') NOT NULL,
  PRIMARY KEY (`idTypSerwisu`),
  UNIQUE INDEX `idTypSerwisu_UNIQUE` (`idTypSerwisu` ASC) VISIBLE,
  UNIQUE INDEX `rodzaj_typ_UNIQUE` (`rodzajSerwisu`, `typPojazdu`) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TransportManager2DB`.`Serwis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManager2DB`.`Serwis` ;

CREATE TABLE IF NOT EXISTS `TransportManager2DB`.`Serwis` (
  `idSerwis` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPojazd` INT UNSIGNED NOT NULL,
  `idTypSerwisu` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `cenaCzesciNetto` INT NULL,
  `robocizna` INT NULL,
  `kosztCalkowityNetto` INT NOT NULL,
  `przebieg` INT NULL,
  `infoDodatkowe` VARCHAR(200) NULL,
  PRIMARY KEY (`idSerwis`),
  UNIQUE INDEX `idSerwisy_UNIQUE` (`idSerwis` ASC) VISIBLE,
  INDEX `idTypSerwisu_idx` (`idTypSerwisu` ASC) VISIBLE,
  INDEX `idPojazd_idx` (`idPojazd` ASC) VISIBLE,
  CONSTRAINT `idPojazd_serwis_fk`
    FOREIGN KEY (`idPojazd`)
    REFERENCES `TransportManager2DB`.`Pojazd` (`idPojazd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTypSerwisu_serwis_fk`
    FOREIGN KEY (`idTypSerwisu`)
    REFERENCES `TransportManager2DB`.`TypSerwisu` (`idTypSerwisu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TransportManager2DB`.`Serwiswidok`
-- -----------------------------------------------------

CREATE OR REPLACE VIEW serwiswidok AS
SELECT 
    serwis.idSerwis,
	typserwisu.rodzajSerwisu,
	pojazd.idPojazd,
	pojazd.typPojazdu,
    pojazd.marka,
    pojazd.model,
    pojazd.nrRejestracyjny,
    serwis.data,
    serwis.cenaCzesciNetto,
    serwis.robocizna,
    serwis.kosztCalkowityNetto,
    serwis.przebieg,
    serwis.infoDodatkowe
FROM 
    serwis
LEFT JOIN 
    pojazd ON serwis.idPojazd = pojazd.idPojazd
LEFT JOIN 
    typserwisu ON serwis.idTypSerwisu = typserwisu.idTypSerwisu;

-- -----------------------------------------------------
-- Table `TransportManager2DB`.`Część`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManager2DB`.`Część` ;

CREATE TABLE IF NOT EXISTS `TransportManager2DB`.`Część` (
  `idCzesc` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idTypSerwisu` INT UNSIGNED NOT NULL,
  `nazwaElementu` VARCHAR(100) NOT NULL,
  `ilosc` INT NOT NULL,
  PRIMARY KEY (`idCzesc`),
  UNIQUE INDEX `idMagazyn_UNIQUE` (`idCzesc` ASC) VISIBLE,
  INDEX `idTypSerwisu_idx` (`idTypSerwisu` ASC) VISIBLE,
  CONSTRAINT `idTypSerwisu_czesc_fk`
    FOREIGN KEY (`idTypSerwisu`)
    REFERENCES `TransportManager2DB`.`TypSerwisu` (`idTypSerwisu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TransportManager2DB`.`WyposażeniePojazdu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransportManager2DB`.`WyposażeniePojazdu` ;

CREATE TABLE IF NOT EXISTS `TransportManager2DB`.`WyposażeniePojazdu` (
  `idWyposazeniePojazdu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPojazd` INT UNSIGNED NOT NULL,
  `opis` VARCHAR(100) NOT NULL,
  `ilosc` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idWyposazeniePojazdu`),
  UNIQUE INDEX `idWyposażeniePojazdu_UNIQUE` (`idWyposazeniePojazdu` ASC) VISIBLE,
  INDEX `idPojazd_idx` (`idPojazd` ASC) VISIBLE,
  CONSTRAINT `idPojazd_wyposazenie_fk`
    FOREIGN KEY (`idPojazd`)
    REFERENCES `TransportManager2DB`.`Pojazd` (`idPojazd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `TransportManager2DB`;

DELIMITER $$

USE `TransportManager2DB`$$
DROP TRIGGER IF EXISTS `TransportManager2DB`.`Serwisy_BEFORE_INSERT` $$
USE `TransportManager2DB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `TransportManager2DB`.`Serwisy_BEFORE_INSERT` BEFORE INSERT ON `Serwis` FOR EACH ROW
BEGIN
IF NEW.kosztCalkowityNetto IS NULL THEN
        SET NEW.kosztCalkowityNetto = COALESCE(NEW.cenaCzesciNetto, 0) + COALESCE(NEW.robocizna, 0);
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TransportManager2DB`.`Kierowca`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManager2DB`;

INSERT INTO `TransportManager2DB`.`Kierowca` (`idKierowca`, `imie`, `nazwisko`, `nrTel`) VALUES 
(1, 'Jan', 'Kowalski', '893938783'),
(2, 'Adam', 'Nowak', '899038713'),
(3, 'Damian', 'Więcek', '563976793'),
(4, 'Grzegorz', 'Brzęczyszczykiewicz', '732982072'),
(5, 'Patryk', 'Karpiński', '567297673'),
(6, 'Marek', 'Błaszczyk', '612398713'),
(7, 'Tomasz', 'Piotrowski', '736839123'),
(8, 'Kamil', 'Szewczyk', '893627812'),
(9, 'Rafał', 'Dąbrowski', '876593728'),
(10, 'Karol', 'Wójcik', '759238715'),
(11, 'Łukasz', 'Kaczmarek', '982173659'),
(12, 'Andrzej', 'Zieliński', '756892374'),
(13, 'Piotr', 'Jankowski', '853672918'),
(14, 'Mariusz', 'Szymański', '782395612'),
(15, 'Artur', 'Grabowski', '693825714'),
(16, 'Paweł', 'Lewandowski', '812736192'),
(17, 'Marcin', 'Czarnecki', '789463281'),
(18, 'Krzysztof', 'Górski', '936578231'),
(19, 'Wojciech', 'Lisowski', '896372581'),
(20, 'Jakub', 'Michałowski', '734589123');

COMMIT;

-- -----------------------------------------------------
-- Data for table `TransportManager2DB`.`Pojazd`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManager2DB`;

INSERT INTO `TransportManager2DB`.`Pojazd` (`idKierowca`, `typPojazdu`, `marka`, `model`, `nrRejestracyjny`, `dodatkoweInf`) VALUES 
(1, 'Ciągnik', 'Volvo', 'FH16', 'PO12345', 'Kolor: czerwony'),
(2, 'Ciągnik', 'Scania', 'R450', 'WA56789', 'Kolor: niebieski'),
(NULL, 'Naczepa', 'Schmitz', 'S.KO', 'GD34567', 'Izoterma'),
(3, 'Naczepa', 'Krone', 'Cool Liner', 'KR67890', 'Chłodnia'),
(4, 'Ciągnik', 'MAN', 'TGX 18.640', 'LU12312', 'Kolor: biały'),
(5, 'Ciągnik', 'DAF', 'XF 530', 'WR54987', 'Kolor: czarny'),
(NULL, 'Naczepa', 'Kögel', 'Cargo', 'ZK89345', 'Kontener'),
(6, 'Ciągnik', 'Iveco', 'S-Way', 'PO34576', 'Kolor: zielony'),
(7, 'Ciągnik', 'Mercedes-Benz', 'Actros 1863', 'GD98765', 'Kolor: szary'),
(NULL, 'Naczepa', 'Fliegl', 'Mega Liner', 'KR54321', 'Mega'),
(8, 'Ciągnik', 'Renault', 'T High', 'PO67890', 'Kolor: żółty'),
(9, 'Ciągnik', 'Volvo', 'FMX', 'WA32198', 'Kolor: srebrny'),
(10, 'Ciągnik', 'Scania', 'S730', 'LU87654', 'Kolor: czarny matowy'),
(NULL, 'Naczepa', 'Krone', 'Box Liner', 'GD43210', 'Na kontenery'),
(11, 'Ciągnik', 'MAN', 'TGS 26.500', 'PO21987', 'Kolor: biały metalik'),
(NULL, 'Ciągnik', 'DAF', 'CF 480', 'WA76543', 'Kolor: niebieski'),
(12, 'Naczepa', 'Kässbohrer', 'F-Light', 'LU39485', 'Lekka konstrukcja'),
(13, 'Ciągnik', 'Iveco', 'Eurocargo', 'KR11223', 'Kolor: pomarańczowy'),
(14, 'Naczepa', 'Schmitz', 'S.CS', 'WR56789', 'Plandeka'),
(NULL, 'Ciągnik', 'Mercedes-Benz', 'Arocs 4148', 'GD98712', 'Kolor: granatowy');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManager2DB`.`TypSerwisu`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManager2DB`;

-- Dodanie wszystkich rekordów do tabeli TypSerwisu 
INSERT INTO `TransportManager2DB`.`TypSerwisu` (`idTypSerwisu`, `rodzajSerwisu`, `typPojazdu`) VALUES
    -- Serwisy dla "Ciągnik"
    (DEFAULT, 'Opony', 'Ciągnik'),
    (DEFAULT, 'Hamulce', 'Ciągnik'),
    (DEFAULT, 'Silnik', 'Ciągnik'),
    (DEFAULT, 'Skrzynia biegów', 'Ciągnik'),
    (DEFAULT, 'Układ wydechowy', 'Ciągnik'),
    (DEFAULT, 'Zawieszenie', 'Ciągnik'),
    (DEFAULT, 'Układ chłodniczy', 'Ciągnik'),
    (DEFAULT, 'Klimatyzacja', 'Ciągnik'),
	(DEFAULT, 'Wnętrze kabiny', 'Ciągnik'),
    (DEFAULT, 'Elektryka', 'Ciągnik'),
    (DEFAULT, 'Wyposażenie', 'Ciągnik'),
    (DEFAULT, 'Serwis olejowy', 'Ciągnik'),
    (DEFAULT, 'Karoseria', 'Ciągnik'),
	(DEFAULT, 'Inne', 'Ciągnik'),


    -- Serwisy dla "Naczepa"
    (DEFAULT, 'Opony', 'Naczepa'),
    (DEFAULT, 'Hamulce', 'Naczepa'),
    (DEFAULT, 'Zawieszenie', 'Naczepa'),
    (DEFAULT, 'Zabudowa', 'Naczepa'),
    (DEFAULT, 'Wyposażenie', 'Naczepa'),
    (DEFAULT, 'Układ chłodniczy', 'Naczepa'),
    (DEFAULT, 'Elektryka', 'Naczepa'),
    (DEFAULT, 'Wymiana podłogi', 'Naczepa'),
	(DEFAULT, 'Inne', 'Naczepa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManager2DB`.`Część`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManager2DB`;

INSERT INTO `TransportManager2DB`.`Część` (`idCzesc`, `idTypSerwisu`, `nazwaElementu`, `ilosc`) VALUES 
-- Części dla ciągników
(DEFAULT, 1, 'Opona 295/80 R22.5 Michelin', 6), 
(DEFAULT, 2, 'Klocki hamulcowe Textar', 2), 
(DEFAULT, 3, 'Pasek klinowy ContiTech', 1), 
(DEFAULT, 4, 'Skrzynia biegów ZF AS Tronic', 1), 
(DEFAULT, 5, 'Tłumik końcowy MAN', 1), 
(DEFAULT, 6, 'Amortyzator pneumatyczny WABCO', 2), 
(DEFAULT, 7, 'Chłodnica silnika DAF', 1), 
(DEFAULT, 8, 'Sprężarka klimatyzacji Sanden', 1), 
(DEFAULT, 9, 'Akumulator Bosch 225Ah', 2), 
(DEFAULT, 10, 'Reflektor LED Hella', 2), 

-- Części dla naczep
(DEFAULT, 11, 'Opona 385/65 R22.5 Goodyear', 4), 
(DEFAULT, 12, 'Hamulce tarczowe WABCO', 2), 
(DEFAULT, 13, 'Resor paraboliczny BPW', 2), 
(DEFAULT, 14, 'Podłoga antypoślizgowa do naczepy', 1), 
(DEFAULT, 15, 'Lampa tylna Hella LED', 4), 
(DEFAULT, 16, 'Hydraulika naczepy Hyva', 1), 
(DEFAULT, 17, 'Siłownik hydrauliczny Hyva', 1), 
(DEFAULT, 18, 'Plandeka boczna 13.6m', 1), 
(DEFAULT, 19, 'Zamek plandeki JOST', 6), 
(DEFAULT, 20, 'Wspornik podnoszenia naczepy', 2);

COMMIT;

-- -----------------------------------------------------
-- Data for table `TransportManager2DB`.`WyposażeniePojazdu`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManager2DB`;

INSERT INTO `TransportManager2DB`.`WyposażeniePojazdu` (`idWyposazeniePojazdu`, `idPojazd`, `opis`, `ilosc`) VALUES 
-- Wyposażenie dla ciągników
(DEFAULT, 1, 'Apteczka DIN 13164', 1), 
(DEFAULT, 2, 'Trójkąt ostrzegawczy', 1), 
(DEFAULT, 3, 'Kamizelka odblaskowa', 2), 
(DEFAULT, 4, 'Radio CB President', 1), 
(DEFAULT, 5, 'Młotek bezpieczeństwa', 1), 
(DEFAULT, 1, 'Łańcuchy śniegowe', 2), 
(DEFAULT, 7, 'Lodówka turystyczna 40L', 1), 
(DEFAULT, 8, 'Zestaw kluczy nasadowych 36 el.', 1), 
(DEFAULT, 1, 'Uchwyt na telefon', 1), 
(DEFAULT, 10, 'Dywaniki gumowe do kabiny', 1), 

-- Wyposażenie dla naczep
(DEFAULT, 11, 'Kliny zabezpieczające koła', 2), 
(DEFAULT, 12, 'Plandeka naprawcza 3x3m', 1), 
(DEFAULT, 13, 'Pas transportowy 5m z grzechotką', 4), 
(DEFAULT, 14, 'Zestaw lamp ostrzegawczych LED', 1), 
(DEFAULT, 15, 'Blokada koła przeciwkradzieżowa', 1), 
(DEFAULT, 16, 'Skrzynka narzędziowa naczepy', 1), 
(DEFAULT, 17, 'Zapasowe żarówki H7', 1), 
(DEFAULT, 18, 'Stabilizator ładunku teleskopowy', 2), 
(DEFAULT, 19, 'Pokrowiec ochronny na plandekę', 1), 
(DEFAULT, 20, 'Smarownica ręczna z tubą', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TransportManager2DB`.`Serwis`
-- -----------------------------------------------------
START TRANSACTION;
USE `TransportManager2DB`;

INSERT INTO `TransportManager2DB`.`Serwis` (`idSerwis`, `idPojazd`, `idTypSerwisu`, `data`, `cenaCzesciNetto`, `robocizna`, `kosztCalkowityNetto`, `przebieg`, `infoDodatkowe`) VALUES 
-- Serwis ciągnika Volvo FH16
(DEFAULT, 1, 1, '2024-11-15', 2400, 600, 3000, 185000, 'Wymiana wszystkich opon na tylnej osi'),
(DEFAULT, 1, 8, '2024-09-05', 750, 300, 1050, 180000, 'Regeneracja sprężarki klimatyzacji'),

-- Serwis naczepy Krone Cool Liner
(DEFAULT, 4, 16, '2024-10-20', 1200, 500, 1700, 240000, 'Naprawa układu chłodniczego, wymiana uszczelki sprężarki'),
(DEFAULT, 4, 15, '2024-12-01', 400, 200, 600, 242500, 'Wymiana lamp tylnych na LED'),

-- Serwis ciągnika Scania S730
(DEFAULT, 10, 3, '2024-11-28', 1400, 800, 2200, 320000, 'Wymiana paska rozrządu i regeneracja pompy wody'),
(DEFAULT, 10, 4, '2024-08-14', 6800, 1200, 8000, 310000, 'Naprawa skrzyni biegów, wymiana łożysk i synchronizatora'),

-- Serwis ciągnika Renault T High
(DEFAULT, 8, 2, '2024-10-12', 800, 450, 1250, 290000, 'Wymiana klocków i tarcz hamulcowych na obu osiach'),

-- Serwis naczepy Kässbohrer F-Light
(DEFAULT, 12, 14, '2024-07-25', 2400, 600, 3000, 210000, 'Montaż nowej podłogi antypoślizgowej'),

-- Serwis ciągnika MAN TGX 18.640
(DEFAULT, 4, 6, '2024-06-15', 1800, 700, 2500, 275000, 'Wymiana amortyzatorów pneumatycznych na osi przedniej'),

-- Serwis naczepy Schmitz S.KO
(DEFAULT, 3, 18, '2024-09-19', 900, 400, 1300, 245000, 'Naprawa plandeki i wymiana zamka na bocznej ścianie'),

-- Serwis ciągnika Mercedes-Benz Actros 1863
(DEFAULT, 7, 13, '2024-05-11', 600, 500, 1100, 190000, 'Regeneracja resorów tylnej osi i wymiana tulei gumowych');

COMMIT;
część
