# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 950)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 165, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 165, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 165, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 165, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setEnabled(True)
        self.frame_main.setGeometry(QtCore.QRect(0, 50, 800, 930))
        self.frame_main.setStyleSheet("QFrame {\n"
"    background-color: #e4eeff; /* Kolor tła prostokąta */\n"
"    color: rgb(228, 238, 255);\n"
"    border: 0px solid #e67e22; /* Obramowanie prostokąta */\n"
"    border-radius: 15px; /* Brak zaokrąglonych rogów, żeby uzyskać prostokąt */\n"
"}\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.widget_buttons = QtWidgets.QWidget(self.frame_main)
        self.widget_buttons.setGeometry(QtCore.QRect(250, 250, 300, 400))
        self.widget_buttons.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* Kolor tła */\n"
"    color: white;  /* Kolor tekstu */\n"
"    border-radius: 10px;  /* Zaokrąglenie rogów */\n"
"    padding: 10px 20px;  /* Wewnętrzne marginesy (dostosowanie rozmiaru) */\n"
"    font-size: 24px;  /* Rozmiar czcionki */\n"
"    font-family: Arial, sans-serif;  /* Czcionka */\n"
"    border: 2px solid #2980b9;  /* Obramowanie */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  /* Kolor tła po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f618d;  /* Kolor tła po kliknięciu */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7;  /* Kolor tła dla nieaktywnych przycisków */\n"
"    color: #7f8c8d;  /* Kolor tekstu dla nieaktywnych przycisków */\n"
"    border: 2px solid #95a5a6;  /* Obramowanie dla nieaktywnych przycisków */\n"
"}\n"
"")
        self.widget_buttons.setObjectName("widget_buttons")
        self.button_flota = QtWidgets.QPushButton(self.widget_buttons)
        self.button_flota.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.button_flota.setObjectName("button_flota")
        self.button_serwis = QtWidgets.QPushButton(self.widget_buttons)
        self.button_serwis.setEnabled(True)
        self.button_serwis.setGeometry(QtCore.QRect(0, 150, 300, 100))
        self.button_serwis.setObjectName("button_serwis")
        self.button_magazyn = QtWidgets.QPushButton(self.widget_buttons)
        self.button_magazyn.setEnabled(True)
        self.button_magazyn.setGeometry(QtCore.QRect(0, 300, 300, 100))
        self.button_magazyn.setObjectName("button_magazyn")
        self.widget_datetime = QtWidgets.QWidget(self.centralwidget)
        self.widget_datetime.setEnabled(True)
        self.widget_datetime.setGeometry(QtCore.QRect(300, 10, 250, 30))
        self.widget_datetime.setStyleSheet("QLabel {\n"
"    color: #ffffff;  /* Kolor tekstu dla etykiet (przykład: pomarańczowy) */\n"
"    background-color: transparent;  /* Przezroczyste tło dla etykiet */\n"
"    border: none;  /* Brak ramki dla etykiet */\n"
"    font-size: 14px;\n"
"    font-weight: bold;  /* Ustawienie pogrubienia tekstu */\n"
"}\n"
"\n"
"")
        self.widget_datetime.setObjectName("widget_datetime")
        self.label_time = QtWidgets.QLabel(self.widget_datetime)
        self.label_time.setGeometry(QtCore.QRect(160, 0, 80, 30))
        self.label_time.setMaximumSize(QtCore.QSize(150, 40))
        self.label_time.setObjectName("label_time")
        self.label_date = QtWidgets.QLabel(self.widget_datetime)
        self.label_date.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.label_date.setMaximumSize(QtCore.QSize(150, 40))
        self.label_date.setObjectName("label_date")
        self.line_vertical_date_time = QtWidgets.QFrame(self.widget_datetime)
        self.line_vertical_date_time.setGeometry(QtCore.QRect(124, 0, 3, 30))
        self.line_vertical_date_time.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;  /* Kolor linii */\n"
"    max-width: 1px;  /* Grubość linii dla linii pionowej */\n"
"}\n"
"\n"
"")
        self.line_vertical_date_time.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_vertical_date_time.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_vertical_date_time.setLineWidth(2)
        self.line_vertical_date_time.setObjectName("line_vertical_date_time")
        self.frame_flota = QtWidgets.QFrame(self.centralwidget)
        self.frame_flota.setEnabled(True)
        self.frame_flota.setGeometry(QtCore.QRect(0, 50, 800, 970))
        self.frame_flota.setStyleSheet("QFrame {\n"
"    background-color: #caf0ef; /* Kolor tła prostokąta */\n"
"    border: 0px solid #e67e22; /* Obramowanie prostokąta */\n"
"    border-radius: 15px; /* Brak zaokrąglonych rogów, żeby uzyskać prostokąt */\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #5d5d5d;\n"
"    background-color: #b9bece; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid #5d5d5d; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 15px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    font-size: 20px;  /* Rozmiar czcionki */\n"
"    font-family: Arial, sans-serif;  /* Czcionka */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a2a6b4; /* Ustawia kolor tła po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8a8e9a;  /* Kolor tła po kliknięciu */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7;  /* Kolor tła dla nieaktywnych przycisków */\n"
"    color: #7f8c8d;  /* Kolor tekstu dla nieaktywnych przycisków */\n"
"    border: 2px solid #95a5a6;  /* Obramowanie dla nieaktywnych przycisków */\n"
"}")
        self.frame_flota.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_flota.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_flota.setObjectName("frame_flota")
        self.widget_flota_header = QtWidgets.QWidget(self.frame_flota)
        self.widget_flota_header.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.widget_flota_header.setStyleSheet("QWidget {\n"
"    background-color: #accccb; /* Kolor tła prostokąta */\n"
"    border: 0px solid #e67e22; /* Obramowanie prostokąta */\n"
"    border-radius: 15px; /* Brak zaokrąglonych rogów, żeby uzyskać prostokąt */\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #5d5d5d;  /* Kolor tekstu dla etykiet (przykład: pomarańczowy) */\n"
"    background-color: transparent;  /* Przezroczyste tło dla etykiet */\n"
"    border: none;  /* Brak ramki dla etykiet */\n"
"    font-size: 20px;\n"
"    font-weight: bold;  /* Ustawienie pogrubienia tekstu */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #a0bebd; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid white; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 15px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    opacity: 0.5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8ea8a7; /* Ustawia kolor tła po najechaniu */\n"
"}")
        self.widget_flota_header.setObjectName("widget_flota_header")
        self.button_exit_flota = QtWidgets.QPushButton(self.widget_flota_header)
        self.button_exit_flota.setEnabled(True)
        self.button_exit_flota.setGeometry(QtCore.QRect(755, 5, 40, 40))
        self.button_exit_flota.setStyleSheet("")
        self.button_exit_flota.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("undo_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_exit_flota.setIcon(icon)
        self.button_exit_flota.setIconSize(QtCore.QSize(30, 30))
        self.button_exit_flota.setObjectName("button_exit_flota")
        self.label_flota_header = QtWidgets.QLabel(self.widget_flota_header)
        self.label_flota_header.setGeometry(QtCore.QRect(300, 10, 200, 30))
        self.label_flota_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flota_header.setObjectName("label_flota_header")
        self.tableView_flota = QtWidgets.QTableView(self.frame_flota)
        self.tableView_flota.setGeometry(QtCore.QRect(50, 150, 700, 650))
        self.tableView_flota.setStyleSheet("    QTableView {\n"
"        border: 2px solid #accccb;\n"
"        border-radius: 15px;\n"
"        background-color: #dff0ef;\n"
"        gridline-color: #95a5a6;\n"
"    }\n"
"\n"
"QTableView::item {\n"
"    border-bottom: 1px solid #bdc3c7;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: #2980b9;\n"
"}")
        self.tableView_flota.setObjectName("tableView_flota")
        self.button_flota_dodaj = QtWidgets.QPushButton(self.frame_flota)
        self.button_flota_dodaj.setGeometry(QtCore.QRect(50, 820, 700, 60))
        self.button_flota_dodaj.setStyleSheet("QPushButton {\n"
"     color: #5d5d5d;\n"
"    background-color: #79cf65; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid #5d5d5d; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 15px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    font-size: 20px;  /* Rozmiar czcionki */\n"
"    font-family: Arial, sans-serif;  /* Czcionka */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6bb558; /* Ustawia kolor tła po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4e8340;  /* Kolor tła po kliknięciu */\n"
"    border: 2px solid #4e8340; /* Ustawia kolor ramki (czarny) */\n"
"\n"
"}")
        self.button_flota_dodaj.setObjectName("button_flota_dodaj")
        self.frame_edit = QtWidgets.QFrame(self.frame_flota)
        self.frame_edit.setGeometry(QtCore.QRect(230, 250, 461, 421))
        self.frame_edit.setStyleSheet("QFrame {\n"
"    background-color: #e6d9c3;\n"
"}\n"
"QPushButton {\n"
"    color: #5d5d5d;\n"
"    background-color: #b9bece; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid #5d5d5d; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 10px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    font-size: 14px;  /* Rozmiar czcionki */\n"
"    font-family: Arial, sans-serif;  /* Czcionka */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a2a6b4; /* Ustawia kolor tła po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8a8e9a;  /* Kolor tła po kliknięciu */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7;  /* Kolor tła dla nieaktywnych przycisków */\n"
"    color: #7f8c8d;  /* Kolor tekstu dla nieaktywnych przycisków */\n"
"    border: 2px solid #95a5a6;  /* Obramowanie dla nieaktywnych przycisków */\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #5d5d5d;  /* Kolor tekstu dla etykiet (przykład: pomarańczowy) */\n"
"    background-color: transparent;  /* Przezroczyste tło dla etykiet */\n"
"    border: none;  /* Brak ramki dla etykiet */\n"
"}")
        self.frame_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_edit.setObjectName("frame_edit")
        self.scrollArea_frame_edit = QtWidgets.QScrollArea(self.frame_edit)
        self.scrollArea_frame_edit.setGeometry(QtCore.QRect(10, 50, 441, 311))
        self.scrollArea_frame_edit.setWidgetResizable(True)
        self.scrollArea_frame_edit.setObjectName("scrollArea_frame_edit")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 311))
        self.scrollAreaWidgetContents.setStyleSheet("QLabel {\n"
"    border: 1px solid #5d5d5d ;  /* Brak ramki dla etykiet */\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_frame_edit = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_frame_edit.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_frame_edit.setObjectName("gridLayout_frame_edit")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_frame_edit.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_frame_edit.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_frame_edit.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_frame_edit.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.scrollArea_frame_edit.setWidget(self.scrollAreaWidgetContents)
        self.button_save = QtWidgets.QPushButton(self.frame_edit)
        self.button_save.setGeometry(QtCore.QRect(160, 370, 120, 28))
        self.button_save.setStyleSheet("QPushButton {\n"
"    background-color: #94e17e; /* Ustawia przezroczyste tło */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #89ce74; /* Ustawia kolor tła po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #70a85f;  /* Kolor tła po kliknięciu */\n"
"}\n"
"\n"
"")
        self.button_save.setObjectName("button_save")
        self.widget_header_frame_edit = QtWidgets.QWidget(self.frame_edit)
        self.widget_header_frame_edit.setGeometry(QtCore.QRect(0, 0, 461, 30))
        self.widget_header_frame_edit.setStyleSheet("QWidget {\n"
"    background: #cfb796;\n"
"    border-radius: 10px;\n"
"} ")
        self.widget_header_frame_edit.setObjectName("widget_header_frame_edit")
        self.label_frame_edit = QtWidgets.QLabel(self.widget_header_frame_edit)
        self.label_frame_edit.setGeometry(QtCore.QRect(190, 10, 81, 16))
        self.label_frame_edit.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;  /* Ustawienie pogrubienia tekstu */\n"
"}")
        self.label_frame_edit.setObjectName("label_frame_edit")
        self.button_exit_frame_edit = QtWidgets.QPushButton(self.widget_header_frame_edit)
        self.button_exit_frame_edit.setEnabled(True)
        self.button_exit_frame_edit.setGeometry(QtCore.QRect(420, 0, 30, 30))
        self.button_exit_frame_edit.setStyleSheet("QPushButton {\n"
"    background-color: #c84043; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid white; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 15px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    opacity: 0.5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a73639; /* Ustawia kolor tła po najechaniu */\n"
"}")
        self.button_exit_frame_edit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("cross_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_exit_frame_edit.setIcon(icon1)
        self.button_exit_frame_edit.setIconSize(QtCore.QSize(15, 15))
        self.button_exit_frame_edit.setObjectName("button_exit_frame_edit")
        self.button_clear = QtWidgets.QPushButton(self.frame_edit)
        self.button_clear.setGeometry(QtCore.QRect(10, 370, 120, 28))
        self.button_clear.setObjectName("button_clear")
        self.button_delete = QtWidgets.QPushButton(self.frame_edit)
        self.button_delete.setGeometry(QtCore.QRect(330, 370, 120, 28))
        self.button_delete.setStyleSheet("QPushButton {\n"
"    background-color: #da6163; /* Ustawia przezroczyste tło */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c54e5a; /* Ustawia kolor tła po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b04652;  /* Kolor tła po kliknięciu */\n"
"}")
        self.button_delete.setObjectName("button_delete")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_flota)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 751, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.button_flota_kierowcy = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_flota_kierowcy.setObjectName("button_flota_kierowcy")
        self.horizontalLayout.addWidget(self.button_flota_kierowcy)
        self.button_flota_naczepy = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_flota_naczepy.setObjectName("button_flota_naczepy")
        self.horizontalLayout.addWidget(self.button_flota_naczepy)
        self.button_flota_ciagniki = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_flota_ciagniki.setObjectName("button_flota_ciagniki")
        self.horizontalLayout.addWidget(self.button_flota_ciagniki)
        self.widget_system = QtWidgets.QWidget(self.centralwidget)
        self.widget_system.setGeometry(QtCore.QRect(710, 5, 85, 40))
        self.widget_system.setObjectName("widget_system")
        self.button_exit = QtWidgets.QPushButton(self.widget_system)
        self.button_exit.setEnabled(True)
        self.button_exit.setGeometry(QtCore.QRect(45, 0, 40, 40))
        self.button_exit.setStyleSheet("QPushButton {\n"
"    background-color: #c84043; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid white; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 15px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    opacity: 0.5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a73639; /* Ustawia kolor tła po najechaniu */\n"
"}")
        self.button_exit.setText("")
        self.button_exit.setIcon(icon1)
        self.button_exit.setIconSize(QtCore.QSize(25, 25))
        self.button_exit.setObjectName("button_exit")
        self.button_minimize = QtWidgets.QPushButton(self.widget_system)
        self.button_minimize.setEnabled(True)
        self.button_minimize.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.button_minimize.setStyleSheet("QPushButton {\n"
"    background-color: #7e95b9; /* Ustawia przezroczyste tło */\n"
"    border: 2px solid white; /* Ustawia kolor ramki (czarny) */\n"
"    border-radius: 15px; /* Zaokrąglone rogi ramki */\n"
"    padding: 5px; /* Wewnętrzne odstępy, opcjonalne */\n"
"    opacity: 0.5;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #627590; /* Ustawia kolor tła po najechaniu */\n"
"}")
        self.button_minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("minus_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimize.setIcon(icon2)
        self.button_minimize.setIconSize(QtCore.QSize(25, 25))
        self.button_minimize.setObjectName("button_minimize")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 250, 30))
        self.label.setStyleSheet("QLabel {\n"
"    color: #ffffff;  /* Kolor tekstu dla etykiet (przykład: pomarańczowy) */\n"
"    background-color: transparent;  /* Przezroczyste tło dla etykiet */\n"
"    border: none;  /* Brak ramki dla etykiet */\n"
"    font-size: 16px;\n"
"    font-weight: bold;  /* Ustawienie pogrubienia tekstu */\n"
"}")
        self.label.setObjectName("label")
        self.widget_datetime.raise_()
        self.frame_main.raise_()
        self.widget_system.raise_()
        self.frame_flota.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_flota.setText(_translate("MainWindow", "FLOTA"))
        self.button_serwis.setText(_translate("MainWindow", "SERWIS"))
        self.button_magazyn.setText(_translate("MainWindow", "MAGAZYN"))
        self.label_time.setText(_translate("MainWindow", "23:55"))
        self.label_date.setText(_translate("MainWindow", "22.10.2024"))
        self.label_flota_header.setText(_translate("MainWindow", "FLOTA"))
        self.button_flota_dodaj.setText(_translate("MainWindow", "DODAJ"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.button_save.setText(_translate("MainWindow", "Zapisz"))
        self.label_frame_edit.setText(_translate("MainWindow", "Edycja"))
        self.button_clear.setText(_translate("MainWindow", "Wyczyść zmiany"))
        self.button_delete.setText(_translate("MainWindow", "Usuń"))
        self.button_flota_kierowcy.setText(_translate("MainWindow", "Kierowcy"))
        self.button_flota_naczepy.setText(_translate("MainWindow", "Naczepy ciężarowe"))
        self.button_flota_ciagniki.setText(_translate("MainWindow", "Ciągniki siodłowe"))
        self.label.setText(_translate("MainWindow", "Aplikacja transportowa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
